### ISSUE TITLE
Moderating one mediation in presence of two mediators

### ISSUE THREAD

**Issue by BDummiesBertinoro** [jamovi-amm/jamm#10]
Hi @mcfanda 
We really like the jAMM module and its 'intelligence' in guessing the model building. 

We may have found one guess estimate too many in presence of two mediators and one (or more) moderator. 

We defined 1 Dependent variable, 2 Mediators, and 2 Covariates. Then, we defined one moderator for **only one** of the two mediators. 
The consequence was that jAMM updated the model including the required interactions. The issue is that jAMM included also the interaction between the moderator and the second mediator (the one we did not want to be moderated). Estimating this interaction should not be required to investigate the moderation of the indirect effect for the only first mediator.

Best wishes,
B.Dummies_Bertinoro

**Comment by mcfanda** [comment]
Thanks a lot for the feedback. You're right, the module suggests an extra path in the case you describe. It will be fixed in the next version. 
Good catch
mc
