### ISSUE TITLE
missing data handling

### ISSUE THREAD

**Issue by denisedoerfel** [jamovi-amm/jamm#12]
Dear Marcello, 
I have an additional question. Since Jamovie-amm is based on lavaan, is there also the possibility of missing data handling integrated (e.g. FIML)?
Thanks again!
Denise.

**Comment by mcfanda** [comment]
Not yet. Up to the current version, only completed cases are used (listwise). We can add FIML (lavaan missing = "ML") in the next version

**Comment by mcfanda** [comment]
version 1.2.0
