### ISSUE TITLE
CI for total effect are the same for normal and bootstrap methods 

### ISSUE THREAD

**Issue by pa0** [jamovi-amm/jamm#16]
We noted that the confidence intervals for the Total effect have the same values for the method based on the normal distribution and the bootstrap method. Shouldn't it be for bootstrap differ depending on the run of the analysis?

**Comment by mcfanda** [comment]
Yes, for the total effect it reports the standard C.I.  Please notice that the total effect is a standard regression path, so bootstrap C.I. are pretty similar to the standard C.I. Nevertheless, this has been fixed in next version (1.2.1). 
Thanks for the hint
