### ISSUE TITLE
bootstrap error?

### ISSUE THREAD

**Issue by c07411994** [jamovi-amm/jamm#22]
Sorry for having posted the question in the wrong place. Let me post it again. A few days ago, I attempted to run the jAMM module on a model with one independent variable (IV), one dependent variable (DV), and three mediators. However, I was unable to obtain bootstrap standard error (se) results and encountered an error message stating "!is.null(BOOT) is not TRUE." I tried repeatedly, but the error persisted.

I also attempted to analyze the same data using the pathj module. In this case, I was able to successfully obtain bootstrap se results.

Does anyone have experience with this error and know how to resolve it? I would be grateful for any assistance in resolving this issue.

Thank you!

P.S. I am using jamovi version 2.4.11 and jAMM version 1.2.3.

**Comment by mcfanda** [comment]
What is your operative system? if it is windows, we can solve it quickly

**Comment by c07411994** [comment]
Yes, my os is windows

**Comment by mcfanda** [comment]
Yes, on Windows, there is an issue with parallely computing the bootstrap CI. I am issuing a new version that fixes, but with no  parallel on Windows.

**Comment by mcfanda** [comment]
Yet

**Comment by c07411994** [comment]
Thanks for the reply. I appreciate your hard work and great contribution to this module. I'm really looking forward to the next update.
