### ISSUE TITLE
erro using syntax from Jamovi into R

### ISSUE THREAD

**Issue by BTunca** [jamovi-amm/jamm#7]
Hi @mcfanda !

I really like the JAMM module in JAMOVI. I am preparing a Markdown document for my analyses in JAMOVI. I managed to install the JAMM package in R and load it, but when I run the syntax from JAMOVI output I get the following error:

"Error: Argument 'dep' contains '#### end ###' which is not present in the dataset"

![image](https://user-images.githubusercontent.com/27208030/80791730-d26bfd00-8b92-11ea-8303-d6c342e11470.png)

Here are all other libraries I load 

![image](https://user-images.githubusercontent.com/27208030/80791818-1f4fd380-8b93-11ea-8c62-4da4fc59ba7f.png)

I appreciate any help,

Thanks again for your work!
/BT

**Comment by mcfanda** [comment]
The R interface of jAMM is very clumsy. I'm working on it but it requires quite some work to make it work fine

**Comment by mcfanda** [comment]
At the moment (version 1.0.4) you can make it work in R not using the formula interface. In your example, you should run it like this:
```
jamm::jammGLM(
  data = data,
  dep = Y,
  mediators = MED,
  covs = "X",
  mediatorsTerms = "X",
  modelTerms = c("MED","X"))

```

In case X is a categorical one, you need to go like this:
```
amm::jammGLM(
  data = data,
  dep = Y,
  mediators = MED,
  factors = "X",
  contrasts = list(list(var="X",type="simple")),
  mediatorsTerms = "X",
  modelTerms = c("MED","X"))

```

I know it's ugly. In the next version one would use the formula interface and it would be much easier
